/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 cube.gltf 
Author: PolyChromic (https://sketchfab.com/PolyChromicDesing)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ice-cube-cb936b6f2df44bea993a33a975544809
Title: Ice Cube
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cube.gltf')
  return (
    <group {...props} dispose={null} scale={2} position={[0, -1 ,0]}>
      <mesh geometry={nodes.pCube1_lambert3_0.geometry} material={materials.lambert3} position={[0, 0.85, 0]} rotation={[-0.087, 0, 0]} />
      <mesh geometry={nodes.pCube2_lambert2_0.geometry} material={materials.lambert2} position={[0, 0.85, 0]} rotation={[-0.087, 0, 0]} />
      <mesh geometry={nodes.pCube3_lambert4_0.geometry} material={materials.lambert4} position={[0.15, 0.25, 0]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes.pCube4_lambert4_0.geometry} material={materials.lambert4} position={[-0.15, 0.25, 0]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes.pCube5_lambert4_0.geometry} material={materials.lambert4} position={[0.525, 0.552, 0]} rotation={[0.087, 0, 0]} scale={[0.05, 0.6, 0.05]} />
      <mesh geometry={nodes.pCube6_lambert4_0.geometry} material={materials.lambert4} position={[-0.53, 0.552, 0]} rotation={[-3.054, 0, -Math.PI]} scale={[0.05, 0.6, 0.05]} />
    </group>
  )
}

useGLTF.preload('/cube.gltf')
